#! /bin/bash

echo "This script is not to be used for creating 3D texture mipmaps."
echo "When I get back to this script it'll evolve more."
exit 1

# A fast and _dirty_ script to generate the mipmaps for the 3D texture. This
# assumes that slice images at mipmap level 0 are 8x8 pixels. IT also assumes
# the 3d texture is 8x8x8.

LOCATION="."

NAME="$LOCATION"

S0="slice_0"
S1="slice_1"
S2="slice_2"
S3="slice_3"
S4="slice_4"
S5="slice_5"
S6="slice_6"
S7="slice_7"

M0="mip_0"
M1="mip_1"
M2="mip_2"
M3="mip_3"

SUFFIX="tiff"

XARGS="-compress Zip -format tiff"
RESIZE="-resize 50%"

# Note: We don't touch the mip_0 images, we just read from them.
# Given 8x8 mip_0 level images, this will produce 44, 2x2, 1x1 images.

# Make slice 0 mipmaps
convert $RESIZE $XARGS "$NAME-$S0-$M0.$SUFFIX" "$NAME-$S0-$M1.$SUFFIX"
convert $RESIZE $XARGS "$NAME-$S0-$M1.$SUFFIX" "$NAME-$S0-$M2.$SUFFIX"
convert $RESIZE $XARGS "$NAME-$S0-$M2.$SUFFIX" "$NAME-$S0-$M3.$SUFFIX"

# Make slice 1 mipmaps
convert $RESIZE $XARGS "$NAME-$S1-$M0.$SUFFIX" "$NAME-$S1-$M1.$SUFFIX"
convert $RESIZE $XARGS "$NAME-$S1-$M1.$SUFFIX" "$NAME-$S1-$M2.$SUFFIX"
convert $RESIZE $XARGS "$NAME-$S1-$M2.$SUFFIX" "$NAME-$S1-$M3.$SUFFIX"

# Make slice 2 mipmaps
convert $RESIZE $XARGS "$NAME-$S2-$M0.$SUFFIX" "$NAME-$S2-$M1.$SUFFIX"
convert $RESIZE $XARGS "$NAME-$S2-$M1.$SUFFIX" "$NAME-$S2-$M2.$SUFFIX"
convert $RESIZE $XARGS "$NAME-$S2-$M2.$SUFFIX" "$NAME-$S2-$M3.$SUFFIX"

# Make slice 3 mipmaps
convert $RESIZE $XARGS "$NAME-$S3-$M0.$SUFFIX" "$NAME-$S3-$M1.$SUFFIX"
convert $RESIZE $XARGS "$NAME-$S3-$M1.$SUFFIX" "$NAME-$S3-$M2.$SUFFIX"
convert $RESIZE $XARGS "$NAME-$S3-$M2.$SUFFIX" "$NAME-$S3-$M3.$SUFFIX"

# Make slice 4 mipmaps
convert $RESIZE $XARGS "$NAME-$S4-$M0.$SUFFIX" "$NAME-$S4-$M1.$SUFFIX"
convert $RESIZE $XARGS "$NAME-$S4-$M1.$SUFFIX" "$NAME-$S4-$M2.$SUFFIX"
convert $RESIZE $XARGS "$NAME-$S4-$M2.$SUFFIX" "$NAME-$S4-$M3.$SUFFIX"

# Make slice 5 mipmaps
convert $RESIZE $XARGS "$NAME-$S5-$M0.$SUFFIX" "$NAME-$S5-$M1.$SUFFIX"
convert $RESIZE $XARGS "$NAME-$S5-$M1.$SUFFIX" "$NAME-$S5-$M2.$SUFFIX"
convert $RESIZE $XARGS "$NAME-$S5-$M2.$SUFFIX" "$NAME-$S5-$M3.$SUFFIX"

# Make slice 6 mipmaps
convert $RESIZE $XARGS "$NAME-$S6-$M0.$SUFFIX" "$NAME-$S6-$M1.$SUFFIX"
convert $RESIZE $XARGS "$NAME-$S6-$M1.$SUFFIX" "$NAME-$S6-$M2.$SUFFIX"
convert $RESIZE $XARGS "$NAME-$S6-$M2.$SUFFIX" "$NAME-$S6-$M3.$SUFFIX"

# Make slice 7 mipmaps
convert $RESIZE $XARGS "$NAME-$S7-$M0.$SUFFIX" "$NAME-$S7-$M1.$SUFFIX"
convert $RESIZE $XARGS "$NAME-$S7-$M1.$SUFFIX" "$NAME-$S7-$M2.$SUFFIX"
convert $RESIZE $XARGS "$NAME-$S7-$M2.$SUFFIX" "$NAME-$S7-$M3.$SUFFIX"
