#! /bin/bash

# A fast and _dirty_ script to generate the mipmaps for the 2d-array example

# NOTE: This assumes that layer images at mipmap level 0 are 1024x1024 pixels.

LOCATION="."

SRCS="bluefur bark rock wiggles"

M0="mip_0"
M1="mip_1"
M2="mip_2"
M3="mip_3"
M4="mip_4"
M5="mip_5"
M6="mip_6"
M7="mip_7"
M8="mip_8"
M9="mip_9"
M10="mip_10"

SUFFIX="tga"

XARGS="-compress None -define tga:image-origin=BottomLeft"
RESIZE="-resize 50%"


for SRC in $SRCS; do
	NAME="$LOCATION/$SRC"
	echo processing "$SRC"
	# TODO: I should have a thing here to detect when the image size is 1x1
	# and then stop automatically. But meh.
	convert $RESIZE $XARGS "$NAME-$M0.$SUFFIX" "$NAME-$M1.$SUFFIX"
	convert $RESIZE $XARGS "$NAME-$M1.$SUFFIX" "$NAME-$M2.$SUFFIX"
	convert $RESIZE $XARGS "$NAME-$M2.$SUFFIX" "$NAME-$M3.$SUFFIX"
	convert $RESIZE $XARGS "$NAME-$M3.$SUFFIX" "$NAME-$M4.$SUFFIX"
	convert $RESIZE $XARGS "$NAME-$M4.$SUFFIX" "$NAME-$M5.$SUFFIX"
	convert $RESIZE $XARGS "$NAME-$M5.$SUFFIX" "$NAME-$M6.$SUFFIX"
	convert $RESIZE $XARGS "$NAME-$M6.$SUFFIX" "$NAME-$M7.$SUFFIX"
	convert $RESIZE $XARGS "$NAME-$M7.$SUFFIX" "$NAME-$M8.$SUFFIX"
	convert $RESIZE $XARGS "$NAME-$M8.$SUFFIX" "$NAME-$M9.$SUFFIX"
	convert $RESIZE $XARGS "$NAME-$M9.$SUFFIX" "$NAME-$M10.$SUFFIX"
done

