(in-package #:defpackage+-user-1)

(defpackage+ #:first-light
  (:nicknames #:fl)
  (:use #:cl)
  (:inherit-from
   #:%first-light
   #:active-camera
   #:actor
   #:actor-component-by-type
   #:actor-components-by-type
   #:attach-component
   #:attach-multiple-components
   #:context
   #:copy-material
   #:delta
   #:deploy-binary
   #:define-component
   #:define-graph
   #:define-material
   #:define-material-profile
   #:define-options
   #:define-resources
   #:define-texture
   #:define-texture-profile
   #:deregister-collider
   #:destroy
   #:destroy-after-time
   #:detach-component
   #:display-id
   #:find-actors-by-id
   #:find-by-uuid
   #:find-components-by-id
   #:find-resource
   #:frame-count
   #:frame-time
   #:general-data-format-descriptor
   #:id
   #:input-data
   #:instances
   #:make-actor
   #:make-component
   #:mat-uniform-ref
   #:on-component-attach
   #:on-component-destroy
   #:on-component-detach
   #:on-component-initialize
   #:on-component-physics-update
   #:on-component-render
   #:on-component-update
   #:on-collision-enter
   #:on-collision-continue
   #:on-collision-exit
   #:option
   #:print-all-resources
   #:project-data
   #:register-collider
   #:shared-storage
   #:spawn-actor
   #:ss-href
   #:start-engine
   #:stop-engine
   #:total-time
   #:ttl
   #:using-material
   #:with-shared-storage)
  (:inherit-from
   #:fl.prefab
   #:define-prefab
   #:define-prefab-descriptor
   #:find-prefab-descriptor
   #:make-prefab-instance
   #:ref))
