(in-package :defpackage+-user-1)

(defpackage+ #:%first-light
  (:nicknames #:%fl)
  (:use #:cl)
  (:export
   #:active-camera
   #:actor
   #:actor-component-by-type
   #:actor-components-by-type
   #:attach-component
   #:attach-multiple-components
   #:cameras
   #:component
   #:context
   #:copy-material
   #:core-state
   #:define-annotation
   #:define-component
   #:define-graph
   #:define-material
   #:define-material-profile
   #:define-options
   #:define-resources
   #:define-scene
   #:define-texture
   #:define-texture-profile
   #:delta
   #:deploy-binary
   #:destroy
   #:detach-component
   #:find-resource
   #:frame-manager
   #:frame-time
   #:general-data-format-descriptor
   #:id
   #:input-data
   #:instances
   #:lookup-material
   #:make-actor
   #:make-component
   #:mat-uniform-ref
   #:on-component-attach
   #:on-component-destroy
   #:on-component-detach
   #:on-component-initialize
   #:on-component-physics-update
   #:on-component-render
   #:on-component-update
   #:option
   #:print-all-resources
   #:project-data
   #:scene-tree
   #:shader
   #:shared-storage
   #:spawn-actor
   #:ss-href
   #:start-engine
   #:state
   #:stop-engine
   #:total-time
   #:using-material
   #:with-shared-storage))
