(in-package #:virality.shaders)

(define-macro mvlet* ((&rest binds) &body body)
  (cond
    ((null binds)
     `(progn ,@body))
    ((listp (car binds))
     (case (length (car binds))
       (0 (error "Need at least one var in a binding list"))
       ((1 2) `(let (,(car binds)) (mvlet* (,@(cdr binds)) ,@body)))
       (t `(multiple-value-bind ,(butlast (car binds)) ,(car (last (car binds)))
             (mvlet* (,@(cdr binds)) ,@body)))))
    ((symbolp (car binds))
     `(let (,(car binds))
        (mvlet* (,@(cdr binds)) ,@body)))))
