* Design Decisions

These are some fundamental design decisions the user should know in order for the engine to function
correctly, listed in no particular order. These should be documented in an obvious way when we ship.

** ASDF system and package naming scheme

The ASDF system and CL package name must be the same. A keyword symbol representing the ASDF system
name, must be the same keyword symbol used to represent the package. In our example, the symbol
=:fl.example= is both a system and package designator, thus it is legal.

** User extension location

Any user extensions should be located in a directory named =data= which is at the same filesystem
level as their own *.asd file. Within this directory, there can be any hierarchy of sub-directories
and files that the user desires, and those file extensions recognized as extensions will be found
and loaded by the engine. It is important that the root directory be named =data= and it be present
next to their *.asd file.

** API considerations

When using the First Light API in your project code, =::= means we do not recommend you use that
symbol. =%= in front of any First Light API symbol means we do not recommend you using it even moreso.
=::%= means stay away from it since it will only cause you pain.
