* Logger

** Overview

First Light uses a very simple logging system that can be used to display messages to the screen, at
various different log levels. For example, when the user runs their game with the =:info= log level,
only messages of level =:info= and higher will be displayed, hiding all =:debug= and =:trace= messages
that would have otherwise been shown. The ordered list of log levels is as follows:

#+BEGIN_SRC lisp
(:trace :debug :info :warn :error :fatal)
#+END_SRC

To define a new log message, open the =logging.lisp= file, and copy one of the existing
=slog:define-message= forms, replacing the log level with the desired level, and a Common Lisp =format=
string. This will define a method that will be called with a variable number of arguments, so feel
free to include any argument substitution =format= directives.

Next, to call this new log message at the desired point in your code, insert the form: =(slog:emit
<name-of-message> arg1 ... argN)=, replacing =<name-of-message>= with the name you chose in the
=slog:define-message=, and passing in any number of arguments, making sure the number of arguments
given matches the argument substitution directives in the =slog:define-message= form.

You can change the log level the game is executed as by editing the =data/settings.cfg= file in the
user's project, creating it if it does not exist, and setting the key =:log-level=. An example minimal
configuration to execute the game with the =:trace= level to see every possible message is as follows:

#+BEGIN_SRC lisp
(:log-level :trace)
#+END_SRC
