* Style Conventions

** General Common Lisp Style

*** Class slots
When writing a new =defclass= form, all slot symbols should be prefixed with =%= and not exported.

*** Class accessors
Please do not define =:accessor= methods for all CLOS slots. Use =:reader=, =:writer=, or =:accessor=,
depending on if the slot should be read-only, write-only, or both.

*** Print debugging
Print debugging is perfectly fine to do offline, but please remove all =print=, =format t=, etc. lines
when committing. If you would like to have important or debugging information printed as output,
please utilize the logging system instead. This allows the user to switch logging levels, and
minimize the noise output. More information is at [[Logger]].

*** Symbol case
Some people like to write certain symbols like =t= or =nil= upper-cased as =T= and =NIL=. For consistency
reasons, please don't do this for any symbols written in source code.

*** Column width
Please set your editor to have a maximum column width of 100.

*** Component Shared Storage
When using the built-in shared storage functionality, a component should follow these rules:

**** Class name
The shared storage for a particular component type should be represented as a class of the name
=<component>-shared-storage=, where =<component>= is the name of the component.

**** Separate file for class and related functions
All shared storage code, including the above class, should be defined in a separate file, named
=shared-storage.lisp=, located within a particular component's directory.
