* User Documentation

This page aims to document the current way to run the engine. It is to be edited when changes to the
API are made. The purpose is to briefly instruct other developers how to use the engine during
development.

1. Start the engine (including the graphics loop)

#+BEGIN_SRC lisp
(ql:quickload :fl.example)
(start-engine :fl.example)
#+END_SRC

This will start the default example scene. If you would like to start a different scene, you can
pass the scene name as an optional second argument to `start-engine`, like so:

#+BEGIN_SRC lisp
(ql:quickload :fl.example)
(start-engine :fl.example 'geometric-volumes)
#+END_SRC

Note: The optional scene name to load should be in the package specified, `:fl-example` in the
example above.

2. Quit the engine

Press =Escape= while the graphics window is focused.

3. Debug the state machine

State machine debugging is disabled by default. To print flow state debugging information to the
REPL each frame, edit the =example/data/settings.cfg= file, changing the key/value pair
=:log-level :debug= to =:log-level :trace=, and then follow step =1= above to start the engine.
