(in-package #:virality-examples)

;;; Prefabs

(v:define-prefab "geometric-volumes" (:library examples)
  (("camera" :copy "/cameras/perspective"))
  (("plane" :copy "/mesh")
   (comp:transform :rotate/velocity (o:make-velocity (v3:vec 1) o:pi)
                   :scale 6f0))
  (("cube" :copy "/mesh")
   (comp:transform :translate (v3:vec 0f0 30f0 0f0)
                   :rotate/velocity (o:make-velocity (v3:vec 1) o:pi)
                   :scale 6f0)
   (comp:mesh :name "cube"))
  (("sphere" :copy "/mesh")
   (comp:transform :translate (v3:vec 0f0 -30f0 0f0)
                   :rotate/velocity (o:make-velocity (v3:vec 1) o:pi)
                   :scale 6f0)
   (comp:mesh :name "sphere"))
  (("torus" :copy "/mesh")
   (comp:transform :translate (v3:vec 30f0 0f0 0f0)
                   :rotate/velocity (o:make-velocity (v3:vec 1) o:pi)
                   :scale 6f0)
   (comp:mesh :name "torus"))
  (("cone" :copy "/mesh")
   (comp:transform :translate (v3:vec -30f0 0f0 0f0)
                   :rotate/velocity (o:make-velocity (v3:vec 1) o:pi)
                   :scale 6f0)
   (comp:mesh :name "cone")
   (comp:render :material 'x:unlit-texture-decal-bright)))
