(in-package #:cl-user)

(defpackage #:virality-examples
  (:local-nicknames
   (#:u #:vutils))
  (:use #:cl)
  (:export
   #:start))

(uiop:define-package #:virality-examples.shader
  (:use #:virality.shader)
  (:export
   #:3d-graph-1
   #:3d-graph-2
   #:art1
   #:art2
   #:art3
   #:art4
   #:art5
   #:art6
   #:damaged-helmet
   #:dynamic-geometry
   #:font
   #:graph
   #:noise
   #:noise-2d/sweep-input
   #:noise/cellular-3d
   #:noise/cellular-fast-3d
   #:noise/cubist-3d
   #:noise/hermite-3d
   #:noise/perlin-3d
   #:noise/perlin-4d
   #:noise/perlin-improved-3d
   #:noise/perlin-surflet-3d
   #:noise/polkadot-3d
   #:noise/polkadot-box-3d
   #:noise/simplex-cellular-3d
   #:noise/simplex-perlin-3d
   #:noise/simplex-polkadot-3d
   #:noise/value-3d
   #:noise/value-4d
   #:noise/value-hermite-3d
   #:noise/value-perlin-3d
   #:ptp-sprite
   #:starfield
   #:unlit-texture-1d
   #:unlit-texture-1d-array
   #:unlit-texture-2d-array
   #:unlit-texture-3d
   #:unlit-texture-cube-map
   #:unlit-texture-cube-map-array))

;; NOTE: This form and many others can be generated by the project skeleton
;; generator
(virality.nicknames:define-nicknames
  (:virality-examples :ex)
  (:virality-examples.shader :ex/shd))
