(in-package #:cl-user)

(defpackage #:virality-examples
  (:local-nicknames
   (#:a #:alexandria)
   (#:u #:golden-utils))
  (:use #:cl)
  (:export #:start))

(uiop:define-package #:virality-examples.shader
  (:use #:virality.shader))

;; NOTE: This form and many others can be generated by the project skeleton
;; generator
(virality.nicknames:define-nicknames
  (:virality-examples :ex)
  (:virality-examples.shader :ex/shd))
