(in-package #:cl-user)

(defpackage #:virality-examples
  (:local-nicknames
   (#:a #:alexandria)
   (#:u #:golden-utils))
  (:use #:cl)
  (:export #:start))

(defpackage #:virality-examples.shaders
  (:use #:shadow.glsl #:umbra.common))

;; NOTE: This form and many others can be generated by the project skeleton
;; generator
(virality.nicknames:define-nicknames
  (:virality-examples :ex)
  (:virality-examples.shaders :ex/shd))
