(in-package #:virality.examples)

;;; Prefabs

(v:define-prefab "geometric-volumes" (:library examples)
  (("camera" :copy "/cameras/perspective"))
  (("plane" :copy "/mesh")
   (c/xform:transform :rotate/inc (o:make-velocity (v3:vec 1) (float pi 1f0))
                      :scale 6f0))
  (("cube" :copy "/mesh")
   (c/xform:transform :translate (v3:vec 0f0 30f0 0f0)
                      :rotate/inc (o:make-velocity (v3:vec 1) (float pi 1f0))
                      :scale 6f0)
   (c/smesh:static-mesh :asset '(:virality.engine/mesh "cube.glb")))
  (("sphere" :copy "/mesh")
   (c/xform:transform :translate (v3:vec 0f0 -30f0 0f0)
                      :rotate/inc (o:make-velocity (v3:vec 1) (float pi 1f0))
                      :scale 6f0)
   (c/smesh:static-mesh :asset '(:virality.engine/mesh "sphere.glb")))
  (("torus" :copy "/mesh")
   (c/xform:transform :translate (v3:vec 30f0 0f0 0f0)
                      :rotate/inc (o:make-velocity (v3:vec 1) (float pi 1f0))
                      :scale 6f0)
   (c/smesh:static-mesh :asset '(:virality.engine/mesh "torus.glb")))
  (("cone" :copy "/mesh")
   (c/xform:transform :translate (v3:vec -30f0 0f0 0f0)
                      :rotate/inc (o:make-velocity (v3:vec 1) (float pi 1f0))
                      :scale 6f0)
   (c/smesh:static-mesh :asset '(:virality.engine/mesh "cone.glb"))
   (c/render:render :material 'x/mat:unlit-texture-decal-bright)))
