(in-package #:virality.examples)

;;; Prefabs

(v:define-prefab "geometric-volumes" (:library examples)
  (("camera" :copy "/cameras/perspective"))
  (("plane" :copy "/mesh")
   (c/xform:transform :rotate/inc (c/xform:angular-velocity (v3:one) pi)
                      :scale 6))
  (("cube" :copy "/mesh")
   (c/xform:transform :translate (v3:vec 0 30 0)
                      :rotate/inc (c/xform:angular-velocity (v3:one) pi)
                      :scale 6)
   (c/smesh:static-mesh :asset '(:virality.engine/mesh "cube.glb")))
  (("sphere" :copy "/mesh")
   (c/xform:transform :translate (v3:vec 0 -30 0)
                      :rotate/inc (c/xform:angular-velocity (v3:one) pi)
                      :scale 6)
   (c/smesh:static-mesh :asset '(:virality.engine/mesh "sphere.glb")))
  (("torus" :copy "/mesh")
   (c/xform:transform :translate (v3:vec 30 0 0)
                      :rotate/inc (c/xform:angular-velocity (v3:one) pi)
                      :scale 6)
   (c/smesh:static-mesh :asset '(:virality.engine/mesh "torus.glb")))
  (("cone" :copy "/mesh")
   (c/xform:transform :translate (v3:vec -30 0 0)
                      :rotate/inc (c/xform:angular-velocity (v3:one) pi)
                      :scale 6)
   (c/smesh:static-mesh :asset '(:virality.engine/mesh "cone.glb"))
   (c/render:render :material 'x/mat:unlit-texture-decal-bright)))

;;; Prefab descriptors

(v:define-prefab-descriptor geometric-volumes ()
  ("geometric-volumes" examples))
