(in-package #:cl-user)

(defpackage #:virality.examples
  (:use #:cl)
  (:export #:start))

(defpackage #:virality.examples.shaders
  (:use #:cl #:vari #:umbra.common))

;; NOTE: This form and many others can be generated by the project skeleton
;; generator
(virality.nicknames:define-nicknames
  (:virality.examples :ex)
  (:virality.examples.shaders :ex/shd))
