(in-package #:cl-user)

(defpackage #:virality.examples
  (:use #:cl)
  (:export #:examples
           #:collision-smoke-test
           #:collision-test-0
           #:collision-test-1
           #:damaged-helmet
           #:geometric-volumes
           #:graph
           #:3d-graph-1
           #:3d-graph-2
           #:isometric-view
           #:noise
           #:sprite-1
           #:sprite-2
           #:texture))

;;;; This is a reasonably scoped shmup that demonstrates use of the engine.
(defpackage #:virality.examples.protect-the-planets
  (:use #:cl)
  (:export #:ptp-base
           #:ptp
           #:starfield-demo))

(defpackage #:virality.examples.shaders
  (:use #:cl #:vari #:virality.shaders))

;; NOTE: This form and many others can be generated by the project skeleton
;; generator
(virality.nicknames:define-nicknames
  (:virality.examples :ex)
  (:virality.examples.protect-the-planets :ex/ptp)
  (:virality.examples.shaders :ex/shd))
