(in-package #:virality.extension)

(tex:define-texture debug-texture (:texture-2d clamp-all-edges)
  ;; I can put overrides in here too specific to this texture.
  (:data #((v::textures v::debug-0)
           (v::textures v::debug-1)
           (v::textures v::debug-2)
           (v::textures v::debug-3)
           (v::textures v::debug-4)
           (v::textures v::debug-5)
           (v::textures v::debug-6)
           (v::textures v::debug-7)
           (v::textures v::debug-8)
           (v::textures v::debug-9)
           (v::textures v::debug-10))))
