(in-package #:virality.contrib.actions)

(defmethod v:on-action-update (action (type (eql 'rotate)))
  (let* ((transform (comp:transform (v:renderer (v:manager action))))
         (attrs (v:attrs action))
         (angle (or (u:href attrs :angle) (* pi 2)))
         (step (u:map-domain 0 1 0 angle (v:action-step action))))
    (ecase (or (u:href attrs :axis) :z)
      (:x (comp:rotate transform (q:orient :local :x step) :replace-p t))
      (:y (comp:rotate transform (q:orient :local :y step) :replace-p t))
      (:z (comp:rotate transform (q:orient :local :z step) :replace-p t)))))

(defmethod v:on-action-finish (action (type (eql 'rotate)))
  (when (v:repeat-p action)
    (v:replace-action action 'rotate/reverse)))

(defmethod v:on-action-update (action (type (eql 'rotate/reverse)))
  (let* ((transform (comp:transform (v:renderer (v:manager action))))
         (attrs (v:attrs action))
         (angle (or (u:href attrs :angle) (* pi 2)))
         (step (- angle (u:map-domain 0 1 0 angle (v:action-step action)))))
    (ecase (or (u:href attrs :axis) :z)
      (:x (comp:rotate transform (q:orient :local :x step) :replace-p t))
      (:y (comp:rotate transform (q:orient :local :y step) :replace-p t))
      (:z (comp:rotate transform (q:orient :local :z step) :replace-p t)))))

(defmethod v:on-action-finish (action (type (eql 'rotate/reverse)))
  (when (v:repeat-p action)
    (v:replace-action action 'rotate)))
