(in-package :%fl)

(defmethod generate-viewport ((display display) position size)
  (with-cfg (window-width window-height) (context (core-state display))
    (let ((map-fn (au:op (au:map-domain 0 1 0 _ _))))
      (v2:with-components ((p position) (s size))
        (gl:viewport (funcall map-fn window-width px)
                     (funcall map-fn window-height py)
                     (funcall map-fn window-width sx)
                     (funcall map-fn window-height sy))))))
